---
- name: Install packages on Debian/Ubuntu
  apt:
    name: "{{ packages_to_install }}"
    state: present
  when: ansible_pkg_mgr == 'apt'
  tags: install

- name: Install packages on RedHat/CentOS/Amazon Linux
  yum:
    name: "{{ packages_to_install }}"
    state: present
  when: ansible_pkg_mgr == 'yum'
  tags: install

- name: Install packages on Fedora
  dnf:
    name: "{{ packages_to_install }}"
    state: present
  when: ansible_pkg_mgr == 'dnf'
  tags: install

- name: Fail if OS is unsupported for package installation
  fail:
    msg: "Unsupported package manager for OS: {{ ansible_os_family }}."
  when: ansible_pkg_mgr not in ['apt', 'yum', 'dnf']
  tags: install
