#cloud-config
users:
  - name: wireguarduser
    gecos: "Wireguard User"
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: sudo
    ssh-authorized-keys:
      - ${ssh_public_key}
    shell: /bin/bash

disable_root: true

ssh_pwauth: false

package_update: true
package_upgrade: true

packages:
  - wireguard

runcmd:
  - iptables -F
  - iptables -P INPUT DROP
  - iptables -P FORWARD DROP
  - iptables -P OUTPUT ACCEPT
  - iptables -A INPUT -i lo -j ACCEPT
  - iptables -A OUTPUT -o lo -j ACCEPT
  - iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  - iptables -A INPUT -p tcp --dport 22 -j ACCEPT
  - iptables -A INPUT -p udp --dport 51820 -j ACCEPT
  - sysctl -w net.ipv4.ip_forward=1
  - iptables -A FORWARD -i wg0 -o enp7s0 -j ACCEPT
  - iptables -A FORWARD -i enp7s0 -o eth0 -j ACCEPT
  - iptables -A FORWARD -i enp7s0 -o wg0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  - iptables -A FORWARD -i eth0 -o enp7s0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  - iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  - iptables -t nat -A POSTROUTING -o enp7s0 -j MASQUERADE
  - |
        cat <<EOT > /etc/wireguard/wg0.conf
        [Interface]
        Address = 10.0.4.5/24
        PrivateKey = $(wg genkey)
        ListenPort = 51820

        [Peer]
        PublicKey = ${wireguard_client_public_key}
        AllowedIPs = 10.0.4.6/32
        EOT
  - systemctl enable wg-quick@wg0
  - systemctl start wg-quick@wg0

